# HTCondor submit file for SN analysis - all batches

executable            = condor/parallel_jobs/wrapper_parallel_sn_analysis.sh
arguments             = $(Process)

output                = condor/parallel_jobs/logs/batch_$(Process)_$(ClusterId).out
error                 = condor/parallel_jobs/logs/batch_$(Process)_$(ClusterId).err
log                   = condor/parallel_jobs/logs/batch_$(Process)_$(ClusterId).log

# GPU resources
request_gpus          = 1
request_memory        = 8GB

+JobFlavour           = "longlunch"
environment           = "LCG_VIEW=/cvmfs/sft.cern.ch/lcg/views/LCG_106a_cuda/x86_64-el9-gcc11-opt"

# No file transfer needed
should_transfer_files = NO

# Notification
notify_user           = evilla@cern.ch
notification          = Error

queue 121
