executable            = run_pure_ed.sh
arguments             = /eos/project-e/ep-nu/public/sn-pointing/$(cat_name) $(cat_name) /eos/home-e/evilla/dune/sn-tps/neural_networks/electron_direction/three_plane_three_plane_v50_100k_20251115_232348/checkpoints/model_epoch_38_val_loss_0.8709.keras /eos/home-e/evilla/dune/sn-tps/neural_networks/electron_direction/three_plane_three_plane_v50_100k_20251115_232348/cosine_energy_pdf.npz results/pure_ed_cats true
output                = ../results/pure_ed_cats/condor_logs/$(cat_name).out
error                 = ../results/pure_ed_cats/condor_logs/$(cat_name).err
log                   = ../results/pure_ed_cats/condor_logs/$(cat_name).log
request_cpus          = 1
request_gpus          = 1
+JobFlavour           = "espresso"
queue cat_name from (
cat000020
)
