executable = scripts/run_cat000001_full_analysis.py
arguments = --cat-dir /eos/project-e/ep-nu/evilla/sn-pointing/cat$(cat_number) --cat-name cat$(cat_number) --pdf-path /eos/home-e/evilla/dune/sn-tps/neural_networks/electron_direction/three_plane_three_plane_v58_200k_lr_schedule_20251118_110931/cosine_energy_pdf.npz --ed-model /eos/home-e/evilla/dune/sn-tps/neural_networks/electron_direction/three_plane_three_plane_v58_200k_lr_schedule_20251118_110931/checkpoints/model_epoch_12_val_loss_0.8898.keras --ct-model /eos/user/e/evilla/dune/sn-tps/neural_networks/channel_tagging/ct_volume_v52_batch_reload_20251116_101125/best_model.keras --scenarios best_case perfect_ct full_pipeline weighted_linear weighted_squared --use-eos-structure

output = logs/cat$(cat_number).out
error = logs/cat$(cat_number).err
log = logs/cat$(cat_number).log

+JobFlavour = "tomorrow"
request_GPUs = 1
request_CPUs = 1

queue cat_number in (3,4,5,6,7,8,9,10,11,12)
