executable            = run_filtered_analysis.sh
arguments             = $(cat_name)
output                = ../results/ed_mcmc_cats/condor_logs/$(cat_name)_filtered.out
error                 = ../results/ed_mcmc_cats/condor_logs/$(cat_name)_filtered.err
log                   = ../results/ed_mcmc_cats/condor_logs/$(cat_name)_filtered.log
request_cpus          = 1
request_gpus          = 1
+JobFlavour           = "microcentury"
queue cat_name from (
cat000030
)
