universe              = vanilla
executable            = /usr/bin/env
arguments             = bash condor/run_cat_scenarios.sh $(cat)
initialdir            = /afs/cern.ch/work/e/evilla/private/dune/refactor-snop-pipeline
should_transfer_files = NO

output                = condor/logs/$(cat).out
error                 = condor/logs/$(cat).err
log                   = condor/logs/$(cat).log

request_cpus          = $(REQUEST_CPUS)
request_memory        = $(REQUEST_MEMORY)
request_disk          = $(REQUEST_DISK)
+JobFlavour           = "$(JOB_FLAVOUR)"

environment = "TEST_N_CC=$(TEST_N_CC);TEST_N_ES=$(TEST_N_ES);OUTPUT_BASE=$(OUTPUT_BASE)"

queue cat from condor/cat_list.txt
