executable              = /afs/cern.ch/work/e/evilla/private/dune/data-selection-pipeline/condor/run_mt_inference_cat000001.sh
arguments               = $(ClusterId) $(ProcId)
output                  = logs/mt_inference_cat000001_$(ClusterId).$(ProcId).out
error                   = logs/mt_inference_cat000001_$(ClusterId).$(ProcId).err
log                     = logs/mt_inference_cat000001_$(ClusterId).log

request_cpus            = 4
request_memory          = 8GB
request_disk            = 2GB

+JobFlavour             = "longlunch"

queue 1
