executable            = condor/run_mt_inference_multicats.sh
output                = logs/mt_inference_multicats_$(ClusterId).$(ProcId).out
error                 = logs/mt_inference_multicats_$(ClusterId).$(ProcId).err
log                   = logs/mt_inference_multicats_$(ClusterId).log
request_cpus          = 4
request_memory        = 8GB
request_disk          = 2GB
+JobFlavour           = "longlunch"
queue
