universe              = vanilla
executable            = /usr/bin/env
arguments             = bash $(RUN_SCRIPT) $(cat)
initialdir            = $(REPO_DIR)
should_transfer_files = NO

output                = $(LOG_DIR)/$(cat).out
error                 = $(LOG_DIR)/$(cat).err
log                   = $(LOG_DIR)/$(cat).log

request_cpus          = $(REQUEST_CPUS)
request_memory        = $(REQUEST_MEMORY)
request_disk          = $(REQUEST_DISK)
+JobFlavour           = "$(JOB_FLAVOUR)"

environment           = "TEST_N_CC=$(TEST_N_CC) TEST_N_ES=$(TEST_N_ES) OUTPUT_BASE=$(OUTPUT_BASE)"

queue cat from $(CAT_LIST)
