# Condor submission file for reprocessing failed categories
executable = scripts/run_single_cat.sh
arguments = $(cat)

log = condor_logs/$(cat)_retry.log
output = condor_logs/$(cat)_retry.out
error = condor_logs/$(cat)_retry.err

request_memory = 32GB
request_gpus = 1
+Requirements = OpSysAndVer =?= "AlmaLinux9"
+JobFlavour = "workday"

queue cat from (
cat000002
cat000003
cat000004
cat000005
cat000006
cat000007
cat000008
cat000009
cat000010
cat000011
cat000012
cat000038
)
